# This file lists the dependencies needed to build and test all of
# preinstalled with:
# conda env create -f environment.yml
name: sage-eulerproduct-build
channels:
  - conda-forge
  - defaults
dependencies:
  - black >=22,<23
  - codespell >=2.2.2,<3
  - gap-defaults
  - ipywidgets
  - jupytext
  - matplotlib-base
  - pip
  - pylint >=2.16,<3
  - pytest
  - pytest-xdist
  - pytest-repeat
  - sagelib
  - libiconv
  # - ruff=0.0.292
  - scipy
  - pycodestyle >=2.9.1,<3
  - pyeantic>=1,<2  # optional: eantic
  - pyexactreal>=3.1.0,<4  # optional: exactreal
