name: Lint
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      
      - uses: conda-incubator/setup-miniconda@v5
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          mamba install -y codespell pycodestyle
          
      - name: Run codespell
        shell: bash -l {0}
        run: codespell `git ls-files`
        
      - name: Run pycodestyle
        shell: bash -l {0}
        # We currently only check for some warnings. We should enable & fix more of them.
        run: pycodestyle --ignore=E203,W503  --max-line-length=256 --select=W2,W3   euler_product/
