name: Lint

on: 
  push:
    branches:
      - main
  pull_request: 
  merge_group:

concurrency:
  # Cancel previous runs of this workflow for the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Merge CI fixes from sage-euleer-prod
      run: |
        .ci/merge-fixes.sh
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      id: deps
      run: pip install tox

    - name: Code style check with pycodestyle
      if: (success() || failure()) && steps.deps.outcome == 'success'
      run: tox -e pycodestyle-minimal

    - name: Code style check with relint
      if: (success() || failure()) && steps.deps.outcome == 'success'
      run: tox -e relint -- euler_prod

    - name: Validate docstring markup as RST
      if: (success() || failure()) && steps.deps.outcome == 'success'
      run: tox -e rst
