name: Test
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { miniforge-variant: "Mambaforge", miniforge-version: "latest", python-version: "3.10" }
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          mamba env update --quiet -n test -f environment.yml
          conda list
      - name: Install sage-euler-product
        shell: bash -l {0}
        run: |
          pip install --verbose --no-index .
      - name: Run doctests
        shell: bash -l {0}
        run: |
          PYTHONPATH=`pwd`/.github/workflows/disable-pytest sage -tp --force-lib --long --optional=sage,pplpy,gmpxxyy euler_product doc
